version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "12321:5432"
    environment:
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_pass
      POSTGRES_DB: flippy
    volumes:
      - ./db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # RabbitMQ server
      - "15672:15672"  # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
