version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "12321:5432"
    environment:
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_pass
      POSTGRES_DB: flippy
    volumes:
      - ./db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
