networks:
  flippy-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "12321:5432"
    environment:
      POSTGRES_USER: ${FLIPPY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FLIPPY_POSTGRES_PASS}
      POSTGRES_DB: ${FLIPPY_POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - flippy-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${FLIPPY_RABBITMQ_PORT}:5672"
      - "${FLIPPY_RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${FLIPPY_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${FLIPPY_RABBITMQ_PASS}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - flippy-network
  book-worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    environment:
      FLIPPY_EDAX_PATH: '/edax-reversi/bin/lEdax-x64'
      FLIPPY_PGN_SOURCE_FOLDERS: ''
      FLIPPY_PGN_TARGET_FOLDER: ''
      FLIPPY_PLAYOK_USERNAMES: ''
      FLIPPY_POSTGRES_DB: ${FLIPPY_POSTGRES_DB}
      FLIPPY_POSTGRES_HOST: postgres # ${FLIPPY_POSTGRES_HOST}
      FLIPPY_POSTGRES_PASS: ${FLIPPY_POSTGRES_PASS}
      FLIPPY_POSTGRES_PORT: 5432 # ${FLIPPY_POSTGRES_PORT}
      FLIPPY_POSTGRES_USER: ${FLIPPY_POSTGRES_USER}
      FLIPPY_RABBITMQ_HOST: rabbitmq # ${FLIPPY_RABBITMQ_HOST}
      FLIPPY_RABBITMQ_PASS: ${FLIPPY_RABBITMQ_PASS}
      FLIPPY_RABBITMQ_PORT: 5672 # ${FLIPPY_RABBITMQ_PORT}
      FLIPPY_RABBITMQ_QUEUE: ${FLIPPY_RABBITMQ_QUEUE}
      FLIPPY_RABBITMQ_USER: ${FLIPPY_RABBITMQ_USER}
      FLIPPY_USERNAMES: ''
    networks:
      - flippy-network
