services:
  test-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pg-test-user
      POSTGRES_PASSWORD: pg-test-password
      POSTGRES_DB: pg-test-db
    ports:
      - "5433:5432"
    networks:
      - flippy-test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pg-test-user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  test-redis:
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - flippy-test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  flippy-test-network:
    driver: bridge
