networks:
  flippy-network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "12321:5432"
    environment:
      POSTGRES_USER: ${FLIPPY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FLIPPY_POSTGRES_PASS}
      POSTGRES_DB: ${FLIPPY_POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - flippy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flippy"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
