services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "12321:5432"
    environment:
      POSTGRES_USER: ${FLIPPY_POSTGRES_USER}
      POSTGRES_PASSWORD: ${FLIPPY_POSTGRES_PASS}
      POSTGRES_DB: ${FLIPPY_POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${FLIPPY_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${FLIPPY_RABBITMQ_PASS}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
