name: Lint and test

on: [push, pull_request]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.3'
    - uses: pdm-project/setup-pdm@v3
      name: Setup PDM
      with:
        python-version: "3.11.3"         # Version range or exact version of a Python version to use, the same as actions/setup-python
        architecture: x64                # The target architecture (x86, x64) of the Python interpreter. the same as actions/setup-python
        version: head
        prerelease: false                # Allow prerelease versions of PDM to be installed
        enable-pep582: false             # Enable PEP 582 package loading globally
        allow-python-prereleases: false  # Allow prerelease versions of Python to be installed. For example if only 3.12-dev is available, 3.12 will fallback to 3.12-dev
    - name: Install dependencies
      run: |
        cd python/flippy
        pdm install
    - name: Run linters
      run: |
        cd python/flippy
        pdm add pre-commit &&
        SKIP=golangci-lint pdm run pre-commit run --all-files
    - name: Run Python tests
      run: |
        cd python/flippy
        pdm install --production
        pdm run pytest --color=yes --cov=src/flippy --cov-report=term-missing -x -vv

  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: 1.24.2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v7
      with:
        version: v2.1.5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Run Go tests
      run: |
        ./test.sh
